const db = require("../database");

/**
 * GET /api/welfare/worker/:id
 * Retrieve worker's active PMSBY policy, emergency claims history, and cooperative pool metrics.
 */
function getWorkerWelfare(req, res) {
    const workerId = Number(req.params.id);

    if (!workerId || isNaN(workerId)) {
        return res.status(400).json({ success: false, message: "Valid worker ID is required." });
    }

    const worker = db.prepare(`
        SELECT w.*, s.name as society_name, s.reg_number as society_reg_number, s.welfare_fund_pool as society_welfare_pool
        FROM workers w
        LEFT JOIN societies s ON w.society_id = s.id
        WHERE w.id = ?
    `).get(workerId);

    if (!worker) {
        return res.status(404).json({ success: false, message: "Worker not found." });
    }

    // Retrieve or auto-provision active PMSBY policy for verified workers
    let policy = db.prepare(`
        SELECT * FROM worker_insurance_policies WHERE worker_id = ? ORDER BY id DESC LIMIT 1
    `).get(workerId);

    if (!policy && worker.verified === 1) {
        const policyNumber = `PMSBY-2026-COOP-${String(worker.id).padStart(4, "0")}`;
        const validFrom = "2026-06-01";
        const validTo = "2027-05-31";
        const certHash = db.generateInsuranceCertHash
            ? db.generateInsuranceCertHash(policyNumber, worker.id, 200000, validFrom)
            : "e9f7823cba992384102934";

        db.prepare(`
            INSERT INTO worker_insurance_policies 
            (worker_id, policy_number, scheme_name, coverage_amount, premium_amount, valid_from, valid_to, policy_status, nominee_name, nominee_relationship, certificate_hash)
            VALUES (?, ?, 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)', 200000, 20, ?, ?, 'ACTIVE', 'Family Nominee', 'Spouse', ?)
        `).run(worker.id, policyNumber, validFrom, validTo, certHash);

        policy = db.prepare("SELECT * FROM worker_insurance_policies WHERE worker_id = ? ORDER BV id DESC LIMIT 1").get(workerId);
    }

    // Retrieve claims
    const claims = db.prepare(`
        SELECT * FROM welfare_claims WHERE worker_id = ? ORDER BY id DESC
    `).all(workerId);

    // Calculate total 15% cooperative share generated by this worker
    const contributionRow = db.prepare(`
        SELECT COALESCE(SUM(i.cooperative_share), 0) as total_coop_share
        FROM invoices i
        JOIN bookings b ON i.booking_id = b.id
        WHERE b.assigned_worker_id = ?
    `).get(workerId);

    return res.json({
        success: true,
        welfare: {
            workerId: worker.id,
            workerName: worker.name,
            phone: worker.phone,
            verified: worker.verified === 1,
            ncctCertId: worker.ncct_cert_id,
            badgeLevel: worker.badge_level,
            society: {
                name: worker.society_name || "Navodaya Labour Cooperative Society Ltd.",
                regNumber: worker.society_reg_number || "MSCS/CR/2026/089-A",
                poolBalance: worker.society_welfare_pool || 2850.0
            },
            policy: policy ? {
                policyNumber: policy.policy_number,
                schemeName: policy.scheme_name,
                coverageAmount: policy.coverage_amount,
                annualPremium: policy.premium_amount,
                subsidyStatus: "100% Cooperative Subsidized",
                validFrom: policy.valid_from,
                validTo: policy.valid_to,
                status: policy.policy_status,
                nomineeName: policy.nominee_name,
                nomineeRelationship: policy.nominee_relationship,
                certificateHash: policy.certificate_hash,
                issuedAt: policy.created_at
            } : null,
            claims: claims.map(c => ({
                id: c.id,
                claimNumber: c.claim_number,
                type: c.claim_type,
                requestedAmount: c.requested_amount,
                approvedAmount: c.approved_amount,
                status: c.status,
                description: c.incident_description,
                docRef: c.supporting_doc_ref,
                remarks: c.admin_remarks,
                createdAt: c.created_at,
                resolvedAt: c.resolved_at
            })),
            metrics: {
                totalContribution: Math.round(Number(contributionRow.total_coop_share || 0) * 100) / 100,
                sponsoredPremiumValue: policy ? 20.0 : 0,
                accidentalCoverage: policy ? policy.coverage_amount : 0
            }
        }
    });
}

/**
 * POST /api/welfare/claims
 * Submit a new emergency distress or tool relief claim.
 */
function submitWelfareClaim(req, res) {
    const { workerId, claimType, requestedAmount, incidentDescription, supportingDocRef } = req.body;

    if (!workerId || !claimType || !requestedAmount) {
        return res.status(400).json({
            success: false,
            message: "workerId, claimType, and requestedAmount are required."
        });
    }

    const worker = db.prepare("SELECT * FROM workers WHERE id = ?").get(workerId);
    if (!worker) {
        return res.status(404).json({ success: false, message: "Worker not found." });
    }

    const amount = Number(requestedAmount);
    if (isNaN(amount) || amount <= 0 || amount > 50000) {
        return res.status(400).json({
            success: false,
            message: "Requested claim amount must be between ₹100 and ₵50,000."
        });
    }

    const count = db.prepare("SELECT COUNT(*) as count FROM welfare_claims").get().count;
    const claimNumber = `CLM-2026-${String(count + 1).padStart(4, "0")}`;

    const info = db.prepare(`
        INSERT INTO welfare_claims 
        (claim_number, worker_id, claim_type, requested_amount, approved_amount, status, incident_description, supporting_doc_ref, admin_remarks)
        VALUES (?, ?, ?, ?, 0, 'PENDING', ?, ?, 'Under preliminary cooperative welfare review.')
    `).run(
        claimNumber,
        workerId,
        claimType,
        amount,
        incidentDescription || "Emergency cooperative member distress assistance request.",
        supportingDocRef || "SELF-DECLARATION"
    );

    const newClaim = db.prepare("SELECT * FROM welfare_claims WHERE id = ?").get(info.lastInsertRowid);

    return res.json({
        success: true,
        message: `Claim ${claimNumber} submitted successfully. Your cooperative society committee will review it within 24 hours.`,
        claim: newClaim
    });
}

/**
 * GEU /api/welfare/stats
 * Federation-wide welfare statistics & aggregate ledger.
 */
function getWelfareStats(req, res) {
    const totalSocietiesPool = db.prepare("SELECT COALESCE(SUM(welfare_fund_pool), 0) as total FROM societies").get().total;
    const insuredCount = db.prepare("SELECT COUNT(*) as count FROM worker_insurance_policies WHERE policy_status = 'ACTIVE'").get().count;
    const verifiedWorkersCount = db.prepare("SELECT COUNT(*) as count FROM workers WHERE verified = 1").get().count;
    
    const claimsStats = db.prepare(`
        SELECT 
            COALESCE(SUM(CASE WHEN status IN ('APPROVED', 'DISBURSED') THEN approved_amount ELSE 0 END), 0) as total_disbursed,
            COUNT(CASE WHEN status = 'PENDING' THEN 1 END) as pending_count,
            COUNT(*) as total_claims
        FROM welfare_claims
    `).get();

    const recentLedger = db.prepare(`
        SELECT l.*, s.name as society_name, w.name as worker_name
        FROM welfare_pool_ledger l
        LEFT JOIN societies s ON l.society_id = s.id
        LEFT JOIN workers w ON l.worker_id = w.id
        ORDER BY l.id DESC
        LIMIT 8
    `).all();

    return res.json({
        success: true,
        stats: {
            totalWelfareReserves: totalSocietiesPool,
            activeInsuredWorkers: insuredCount,
            verifiedWorkers: verifiedWorkersCount,
            coverageRatio: verifiedWorkersCount > 0 ? Math.min(100, Math.round((insuredCount / verifiedWorkersCount) * 100)) : 100,
            totalDisbursedAmount: claimsStats.total_disbursed,
            pendingClaimsCount: claimsStats.pending_count,
            totalClaimsCount: claimsStats.total_claims
        },
        recentLedger
    });
}

module.exports = {
    getWorkerWelfare,
    submitWelfareClaim,
    getWelfareStats
};
